[package]
name = "rustlox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
rustyline = "14.0.0"
strum_macros = "0.26.2"
thiserror = "1.0.60"

[[bin]]
name = "lox"
path = "src/main.rs"

